import { Image } from 'expo-image';
import { Href, router } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { CaptureHeader } from '@/src/components/capture/capture-header';
import { ProcessingChecklist } from '@/src/components/capture/processing-checklist';
import { RecordingPlaybackBar } from '@/src/components/capture/recording-playback-bar';
import { PrimaryButton } from '@/src/components/onboarding/primary-button';
import { formatBobbleDateLabel } from '@/src/features/bobbles/format';
import { categoryFromCaptureKind } from '@/src/features/bobbles/types';
import { CAPTURE_COPY, useCaptureStore } from '@/src/store/capture-store';
import { Typography } from '@/src/theme/fonts';

const PROCESSING_TEXT = '#17164B';
const PROCESSING_MASCOT = require('@/src/assets/images/bobble-dualSound.png');

const PROCESSING_AUTO_ADVANCE = true;

const STEPS = [
  { id: 'listen', label: 'Listening to your Bobble...', icon: 'ear' },
  { id: 'points', label: 'Finding the key points...', icon: 'list' },
  { id: 'connect', label: 'Connecting your ideas...', icon: 'lightbulb' },
  { id: 'ready', label: 'Almost ready!', icon: 'bobble' },
] as const;

export default function ProcessingScreen() {
  const insets = useSafeAreaInsets();
  const [completedCount, setCompletedCount] = useState(0);
  const isComplete = completedCount >= STEPS.length;
  const recordingUri = useCaptureStore((state) => state.recordingUri);
  const recordingDurationSeconds = useCaptureStore((state) => state.recordingDurationSeconds);
  const clearRecording = useCaptureStore((state) => state.clearRecording);

  const handleSaveBobble = useCallback(() => {
    const durationSec = recordingDurationSeconds > 0 ? recordingDurationSeconds : 60;
    const durationMin = Math.max(1, Math.round(durationSec / 60));
    const captureKind = useCaptureStore.getState().captureKind;
    const copy = CAPTURE_COPY[captureKind];

    // Tasks are generated by OpenAI from the AssemblyAI transcript on save.
    useCaptureStore.getState().setPendingBobbleSave({
      title: copy.title,
      dateLabel: formatBobbleDateLabel(new Date().toISOString()),
      durationMin,
      durationSec,
      category: categoryFromCaptureKind(captureKind),
      tasks: [],
    });

    router.replace('/capture/saving' as Href);
  }, [recordingDurationSeconds]);

  useEffect(() => {
    if (!PROCESSING_AUTO_ADVANCE || isComplete) return;

    const timeout = setTimeout(() => {
      setCompletedCount((prev) => prev + 1);
    }, 900);

    return () => clearTimeout(timeout);
  }, [completedCount, isComplete]);

  return (
    <View
      style={[
        styles.root,
        {
          paddingTop: insets.top + 8,
          paddingBottom: insets.bottom + 24,
        },
      ]}
    >
      <CaptureHeader
        leftLabel="Discard"
        onLeftPress={() => {
          clearRecording();
          router.replace('/(tabs)' as Href);
        }}
      />

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.hero}>
          <Text style={styles.title}>
            {isComplete ? 'Ready to turn this into tasks' : 'Bobble is listening...'}
          </Text>
          <Text style={styles.subtitle}>
            {isComplete
              ? 'I’ll transcribe your recording and suggest actions from what you said.'
              : 'Sit tight while I work my magic'}
          </Text>
        </View>

        <View style={styles.mascotWrap}>
          <Image source={PROCESSING_MASCOT} style={styles.mascot} contentFit="contain" />
        </View>

        {recordingUri ? (
          <View style={styles.playbackWrap}>
            <RecordingPlaybackBar uri={recordingUri} durationSeconds={recordingDurationSeconds} />
          </View>
        ) : null}

        {!isComplete ? (
          <ProcessingChecklist steps={STEPS} completedCount={completedCount} />
        ) : null}
      </ScrollView>

      {isComplete ? (
        <View style={styles.actions}>
          <PrimaryButton
            label="Save Bobble"
            style={styles.primaryAction}
            onPress={handleSaveBobble}
          />
        </View>
      ) : (
        <Text style={styles.footer}>This usually takes 10–20 seconds</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    paddingHorizontal: 24,
  },
  hero: {
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    marginBottom: 8,
  },
  title: {
    ...Typography.heading,
    fontSize: 26,
    lineHeight: 34,
    color: PROCESSING_TEXT,
    textAlign: 'center',
  },
  subtitle: {
    ...Typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: PROCESSING_TEXT,
    textAlign: 'center',
    opacity: 0.85,
  },
  mascotWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mascot: {
    width: 300,
    height: 224,
    backgroundColor: 'transparent',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 16,
    gap: 16,
  },
  playbackWrap: {
    width: '100%',
  },
  actions: {
    marginTop: 'auto',
    paddingTop: 12,
  },
  primaryAction: {
    width: '100%',
  },
  footer: {
    ...Typography.body,
    fontFamily: Typography.button.fontFamily,
    color: PROCESSING_TEXT,
    textAlign: 'center',
    marginTop: 'auto',
    paddingTop: 12,
  },
});
